version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: ci         # 앞서 만든 multi‑stage 이미지
    ports:
      - "8080:80"                             
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost"]
      interval: 5s
      timeout: 2s
      retries: 5
